### ISSUE TITLE
[Frontend] Remove unnecessary directories 🗑️ 

### ISSUE THREAD

**Issue by EmperorYP7** [EmperorYP7/CoviSource#17]
### Description

The current `frontend-dev` branch has a lot of unused directories which we would like to get rid of.

### Screenshots/Testimonials

NA

### Resources

Look at [./src/components](https://github.com/EmperorYP7/CoviSource/tree/frontend/src/components) and try to find unused components and chop em off! 🤺 

---

For frontend, kindly go through contribution guidelines for frontend &
create a PR to `frontend-dev`.

For backend, kindly go through contribution guidelines for backend &
create a PR to `backend-dev`.

**Comment by sb2356-iiitr** [comment]
Hey @EmperorYP7 I would like to work on this!

**Comment by EmperorYP7** [comment]
Sure! :smile:

**Comment by EmperorYP7** [comment]
What the progress on this @sb2356-iiitr?

**Comment by sb2356-iiitr** [comment]
I am on it.

**Comment by EmperorYP7** [comment]
Closing against #33
